import { useEffect, useMemo, useState, type ReactNode } from "react";
import { motion } from "framer-motion";
import { Accessibility, Activity, CheckCircle2, ExternalLink, Gauge, Heading1, Keyboard, Monitor, RefreshCw, ShieldCheck, Smartphone, Tablet } from "lucide-react";
import { Eyebrow, Section, SectionIntro } from "@/components/blocks";
import { Reveal } from "@/components/Reveal";
import { navigate } from "@/router";

type CardProps = { children: ReactNode; className?: string };
function Card({ children, className = "" }: CardProps) {
  return <div className={`rounded-[1.8rem] border border-white/[0.08] bg-white/[0.025] ${className}`}>{children}</div>;
}

function SeoLab() {
  const [tab, setTab] = useState("serp");
  const [title, setTitle] = useState("Web Design Pampanga | Custom Business Websites");
  const [description, setDescription] = useState("Fast, mobile-first websites for Pampanga businesses with strong SEO foundations and clearer conversion paths.");
  const tabs = [["serp","SERP"],["schema","Schema"],["headings","Headings"],["links","Internal links"]] as const;
  return <Card className="p-6 sm:p-8">
    <p className="font-mono text-[10px] uppercase tracking-[.2em] text-gold-400">SEO Lab</p>
    <h3 className="mt-3 font-display text-2xl font-bold text-white">See the search structure before launch.</h3>
    <div className="mt-5 flex flex-wrap gap-2">{tabs.map(([id,label]) => <button key={id} type="button" onClick={() => setTab(id)} className={`rounded-full border px-3 py-2 text-xs ${tab===id?"border-gold-400/40 bg-gold-400/[.08] text-gold-200":"border-white/10 text-slate-500"}`}>{label}</button>)}</div>
    {tab === "serp" && <div className="mt-6 grid gap-4 lg:grid-cols-2"><div className="space-y-3"><input value={title} onChange={e=>setTitle(e.target.value)} className="w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-sm text-white outline-none"/><textarea value={description} onChange={e=>setDescription(e.target.value)} rows={4} className="w-full resize-none rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-sm text-white outline-none"/></div><div className="rounded-xl bg-white p-5 text-slate-900"><p className="text-xs text-slate-600">webdesignpampanga.com › services</p><p className="mt-2 text-xl text-[#1a0dab]">{title}</p><p className="mt-2 text-sm text-slate-700">{description}</p></div></div>}
    {tab === "schema" && <div className="mt-6 grid gap-4 lg:grid-cols-2"><pre className="overflow-x-auto rounded-xl bg-black/30 p-5 text-xs leading-6 text-slate-300"><code>{`{\n  "@context": "https://schema.org",\n  "@type": "ProfessionalService",\n  "name": "Web Design Pampanga",\n  "serviceType": ["Web Design", "SEO"]\n}`}</code></pre><ul className="space-y-3 rounded-xl border border-white/[.08] p-5 text-sm text-slate-400">{["Supported schema only","Business details must match","No invented ratings","Validate before launch"].map(x=><li key={x} className="flex gap-2"><CheckCircle2 className="h-4 w-4 text-gold-400"/>{x}</li>)}</ul></div>}
    {tab === "headings" && <div className="mt-6 space-y-2 rounded-xl bg-black/20 p-5 font-mono text-xs"><div className="rounded-lg border border-gold-400/30 p-3 text-gold-200">H1 · Web Design Pampanga</div><div className="ml-4 rounded-lg border border-white/10 p-3 text-slate-300">H2 · Website design services</div><div className="ml-8 rounded-lg border border-white/[.07] p-3 text-slate-500">H3 · Business websites</div><div className="ml-4 rounded-lg border border-white/10 p-3 text-slate-300">H2 · Why choose the studio</div></div>}
    {tab === "links" && <div className="mt-6 grid gap-3 sm:grid-cols-2">{[["Homepage","Web design services"],["Service","Pricing"],["Blog","Local SEO service"],["Location","Portfolio"]].map(([from,to])=><div key={from} className="rounded-xl border border-white/[.08] p-4"><p className="text-[10px] uppercase text-slate-600">{from}</p><p className="mt-2 text-sm font-semibold text-gold-300">→ {to}</p></div>)}</div>}
  </Card>;
}

function ConversionLab() {
  const [hero,setHero]=useState(true), [cta,setCta]=useState(true), [fields,setFields]=useState(4), [nav,setNav]=useState(5);
  const score=useMemo(()=>Math.min(100,46+(hero?18:0)+(cta?18:0)+Math.max(0,10-Math.abs(fields-4)*3)+Math.max(0,8-Math.max(0,nav-6)*2)),[hero,cta,fields,nav]);
  return <Card className="p-6 sm:p-8"><p className="font-mono text-[10px] uppercase tracking-[.2em] text-sky-300">Conversion Lab</p><h3 className="mt-3 font-display text-2xl font-bold text-white">Change the page. Watch the decision path change.</h3><p className="mt-2 text-sm text-slate-500">Illustrative CRO teaching score, not a promised conversion rate.</p><div className="mt-6 grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div className="space-y-3"><button onClick={()=>setHero(v=>!v)} className="flex w-full justify-between rounded-xl border border-white/10 p-3 text-sm text-slate-300">Specific hero <span>{hero?"On":"Off"}</span></button><button onClick={()=>setCta(v=>!v)} className="flex w-full justify-between rounded-xl border border-white/10 p-3 text-sm text-slate-300">Strong CTA <span>{cta?"On":"Off"}</span></button><label className="block text-xs text-slate-500">Form fields: {fields}<input type="range" min="2" max="10" value={fields} onChange={e=>setFields(Number(e.target.value))} className="mt-2 w-full"/></label><label className="block text-xs text-slate-500">Navigation items: {nav}<input type="range" min="3" max="10" value={nav} onChange={e=>setNav(Number(e.target.value))} className="mt-2 w-full"/></label></div><div className="rounded-2xl border border-white/[.08] bg-black/20 p-5"><p className="text-[10px] uppercase text-slate-600">Decision-path clarity</p><p className="mt-2 font-display text-5xl font-bold text-white">{score}</p><h4 className="mt-6 font-display text-2xl font-bold text-white">{hero?"Websites built to generate qualified enquiries.":"Welcome to our website."}</h4><button className={`mt-5 rounded-full px-5 py-3 text-sm font-bold ${cta?"bg-gold-400 text-ink-950":"border border-white/10 text-slate-500"}`}>{cta?"Request a website review":"Learn more"}</button></div></div></Card>;
}

export function SeoConversionLabsSection() {
  const [mode,setMode]=useState<"seo"|"cro">("seo");
  return <Section id="lab" ambient divider><div className="flex flex-col gap-6 sm:flex-row sm:items-end sm:justify-between"><SectionIntro eyebrow="SEO + Conversion Lab" title={<>Prove the thinking behind the <span className="text-gold-gradient">design.</span></>} description="Interactive examples for search structure and conversion decisions."/><div className="flex rounded-full border border-white/10 p-1"><button onClick={()=>setMode("seo")} className={`rounded-full px-4 py-2 text-xs ${mode==="seo"?"bg-white/10 text-white":"text-slate-500"}`}>SEO Lab</button><button onClick={()=>setMode("cro")} className={`rounded-full px-4 py-2 text-xs ${mode==="cro"?"bg-white/10 text-white":"text-slate-500"}`}>Conversion Lab</button></div></div><div className="mt-10">{mode==="seo"?<SeoLab/>:<ConversionLab/>}</div></Section>;
}

const breakpoints=[["1440",1440,Monitor],["1024",1024,Monitor],["768",768,Tablet],["390",390,Smartphone]] as const;
const inspector=["Responsive grid","Schema","Lazy loaded","Accessible button","Conversion CTA"] as const;
export function ResponsiveInspectorSection() {
  const [bp,setBp]=useState(1440), [selected,setSelected]=useState(0);
  return <Section divider><div className="grid gap-10 lg:grid-cols-[1.25fr_.75fr] lg:gap-14"><Reveal><Card className="p-5 sm:p-7"><div className="flex flex-wrap gap-2">{breakpoints.map(([label,width,Icon])=><button key={label} onClick={()=>setBp(width)} className={`inline-flex items-center gap-2 rounded-full border px-3 py-2 text-xs ${bp===width?"border-gold-400/40 text-gold-200":"border-white/10 text-slate-500"}`}><Icon className="h-3.5 w-3.5"/>{label}px</button>)}</div><motion.div animate={{width:`${Math.max(28,bp/1440*100)}%`}} className="mx-auto mt-6 overflow-hidden rounded-2xl border border-white/10 bg-white text-slate-900"><div className="flex items-center justify-between border-b border-slate-200 p-4"><span className="h-3 w-20 rounded bg-slate-300"/><div className={bp<=768?"hidden":"flex gap-2"}>{[1,2,3].map(x=><span key={x} className="h-2 w-8 rounded bg-slate-200"/>)}</div></div><div className={`grid gap-3 p-4 ${bp>=1024?"grid-cols-[1.1fr_.9fr]":"grid-cols-1"}`}><div><div className="h-3 w-20 rounded bg-amber-300"/><h3 className="mt-3 text-xl font-bold">Responsive system</h3><div className="mt-3 h-2 w-full rounded bg-slate-200"/><div className="mt-2 h-2 w-4/5 rounded bg-slate-200"/></div><div className="min-h-24 rounded-xl bg-slate-200"/></div></motion.div></Card></Reveal><Reveal delay={.08}><Card className="p-6"><p className="font-mono text-[10px] uppercase tracking-[.2em] text-gold-400">Live design inspector</p><div className="mt-5 space-y-2">{inspector.map((x,i)=><button key={x} onClick={()=>setSelected(i)} className={`w-full rounded-xl border px-4 py-3 text-left text-sm ${selected===i?"border-gold-400/35 bg-gold-400/[.07] text-white":"border-white/[.07] text-slate-500"}`}>{x}</button>)}</div><p className="mt-5 rounded-xl bg-black/20 p-4 text-sm text-slate-400">{["Columns collapse deliberately instead of simply shrinking.","Structured data uses supported types and matching business facts.","Below-the-fold images can defer loading to protect the first screen.","Real button semantics, keyboard focus and accessible names are preserved.","The primary action stays obvious while secondary paths remain available."][selected]}</p></Card></Reveal></div></Section>;
}

type AuditState={performance:number;accessibility:number;seo:number;bestPractices:number;sections:{label:string;status:string;detail:string}[]};
function scoreClass(n:number){return n>=90?"text-emerald-300":n>=70?"text-amber-300":"text-rose-300";}
export function WebsiteAuditSection() {
  const [url,setUrl]=useState(""),[loading,setLoading]=useState(false),[error,setError]=useState(""),[result,setResult]=useState<AuditState|null>(null);
  const run=async()=>{const target=/^https?:\/\//i.test(url.trim())?url.trim():`https://${url.trim()}`;if(!url.trim()){setError("Enter a website URL first.");return;}try{new URL(target);}catch{setError("That URL does not look valid.");return;}setLoading(true);setError("");try{const r=await fetch(`https://www.googleapis.com/pagespeedonline/v5/runPagespeed?url=${encodeURIComponent(target)}&strategy=mobile&category=performance&category=accessibility&category=seo&category=best-practices`);if(!r.ok)throw 0;const d=await r.json(),c=d?.lighthouseResult?.categories??{},a=d?.lighthouseResult?.audits??{};const status=(key:string)=>typeof a[key]?.score==="number"?(a[key].score>=.9?"Pass":"Review"):"Manual";setResult({performance:Math.round((c.performance?.score??0)*100),accessibility:Math.round((c.accessibility?.score??0)*100),seo:Math.round((c.seo?.score??0)*100),bestPractices:Math.round((c["best-practices"]?.score??0)*100),sections:[{label:"Performance",status:"Live",detail:a["largest-contentful-paint"]?.displayValue||"Lighthouse performance checks"},{label:"SEO basics",status:"Live",detail:`SEO score ${Math.round((c.seo?.score??0)*100)}`},{label:"Mobile",status:status("viewport"),detail:"Viewport and mobile usability checks"},{label:"HTTPS",status:status("is-on-https"),detail:target.startsWith("https://")?"HTTPS URL supplied":"Review HTTPS"},{label:"Metadata",status:status("meta-description"),detail:`Title: ${status("document-title")} · Description: ${status("meta-description")}`},{label:"Headings",status:status("heading-order"),detail:"Heading-order audit where available"},{label:"Schema",status:"Manual",detail:"Confirm supported markup in Google's Rich Results test"},{label:"Conversion",status:"Manual",detail:"Review hero clarity, CTA hierarchy, form length and trust signals"}]});sessionStorage.setItem("wdp_audit_url",target);}catch{setError("Google's live audit is unavailable or rate-limited. Try again shortly.");}finally{setLoading(false);}};
  return <Section id="website-audit" ambient divider><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr] lg:gap-14"><div><Reveal><Eyebrow>Roast my website</Eyebrow></Reveal><Reveal delay={.08}><h2 className="mt-5 font-display text-3xl font-bold text-white sm:text-4xl">A website audit beyond one <span className="text-gold-gradient">speed score.</span></h2></Reveal><p className="mt-5 text-base leading-relaxed text-slate-400">Performance, SEO basics, mobile, HTTPS, metadata, headings, schema and conversion are separated so the result is easier to act on.</p></div><Reveal><Card className="p-6 sm:p-8"><div className="flex flex-col gap-3 sm:flex-row"><input value={url} onChange={e=>setUrl(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void run();}} placeholder="yourwebsite.com" className="min-w-0 flex-1 rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-sm text-white outline-none"/><button onClick={()=>void run()} disabled={loading} className="inline-flex items-center justify-center gap-2 rounded-xl bg-gold-400 px-5 py-3 text-sm font-bold text-ink-950"><Gauge className={`h-4 w-4 ${loading?"animate-spin":""}`}/>{loading?"Auditing…":"Roast my website"}</button></div>{error&&<p className="mt-3 text-sm text-amber-300">{error}</p>}{result&&<><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Performance",result.performance],["Accessibility",result.accessibility],["SEO",result.seo],["Best practices",result.bestPractices]].map(([label,n])=><div key={String(label)} className="rounded-xl border border-white/[.08] p-4 text-center"><p className={`text-2xl font-bold ${scoreClass(Number(n))}`}>{n}</p><p className="mt-1 text-[9px] uppercase text-slate-600">{label}</p></div>)}</div><div className="mt-5 grid gap-2 sm:grid-cols-2">{result.sections.map(x=><div key={x.label} className="rounded-xl border border-white/[.07] p-4"><div className="flex justify-between gap-3"><span className="text-sm font-semibold text-white">{x.label}</span><span className="text-[10px] uppercase text-gold-400">{x.status}</span></div><p className="mt-2 text-xs leading-relaxed text-slate-500">{x.detail}</p></div>)}</div><button onClick={()=>navigate("/contact/")} className="mt-5 rounded-full bg-gold-400 px-5 py-3 text-sm font-bold text-ink-950">Send me this URL</button></>}</Card></Reveal></div></Section>;
}

export function LiveLighthouseSection() {
  const [scores,setScores]=useState<number[]|null>(null),[state,setState]=useState<"idle"|"loading"|"error">("idle");
  const load=async()=>{setState("loading");try{const r=await fetch(`https://www.googleapis.com/pagespeedonline/v5/runPagespeed?url=${encodeURIComponent("https://webdesignpampanga.com/")}&strategy=mobile&category=performance&category=accessibility&category=seo&category=best-practices`);if(!r.ok)throw 0;const c=(await r.json())?.lighthouseResult?.categories??{};setScores([c.performance,c.accessibility,c.seo,c["best-practices"]].map((x:any)=>Math.round((x?.score??0)*100)));setState("idle");}catch{setState("error");}};useEffect(()=>{void load();},[]);
  return <Section divider><div className="grid gap-10 lg:grid-cols-[.78fr_1.22fr] lg:items-center"><div><Reveal><Eyebrow>Live Lighthouse proof</Eyebrow></Reveal><h2 className="mt-5 font-display text-3xl font-bold text-white sm:text-4xl">No hard-coded performance <span className="text-gold-gradient">badges.</span></h2><p className="mt-5 text-slate-400">Scores are requested live for this website. If Google is rate-limited, the UI says so.</p><a href="https://pagespeed.web.dev/analysis?url=https%3A%2F%2Fwebdesignpampanga.com%2F" target="_blank" rel="noopener noreferrer" className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-gold-400">Open Google report <ExternalLink className="h-4 w-4"/></a></div><Card className="p-6"><div className="flex justify-between"><span className="text-sm font-semibold text-white">webdesignpampanga.com</span><button onClick={()=>void load()} className="inline-flex items-center gap-2 text-xs text-slate-500"><RefreshCw className={`h-3.5 w-3.5 ${state==="loading"?"animate-spin":""}`}/>Refresh</button></div>{scores?<div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">{["Performance","Accessibility","SEO","Best practices"].map((x,i)=><div key={x} className="rounded-xl border border-white/[.08] p-4 text-center"><p className={`text-2xl font-bold ${scoreClass(scores[i])}`}>{scores[i]}</p><p className="mt-1 text-[9px] uppercase text-slate-600">{x}</p></div>)}</div>:<div className="mt-6 rounded-xl border border-white/[.07] p-6 text-sm text-slate-500">{state==="error"?"Live scores unavailable or rate-limited.":"Requesting live scores…"}</div>}</Card></div></Section>;
}

export function BuildQualitySection() {
  const checks=["Responsive QA","Broken links","Forms","Analytics","Search Console","Schema","Redirects","Core Web Vitals"];
  const access=[[Keyboard,"Keyboard navigation"],[Heading1,"Semantic HTML"],[Activity,"Reduced motion"],[Accessibility,"Contrast + accessible names"]] as const;
  return <Section ambient divider><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><Reveal><Eyebrow>Build-quality dashboard</Eyebrow></Reveal><h2 className="mt-5 font-display text-3xl font-bold text-white sm:text-4xl">The launch checklist should be as visible as the <span className="text-gold-gradient">design.</span></h2><p className="mt-5 text-slate-400">The site is not considered ready because the homepage looks finished.</p><div className="mt-6 rounded-xl border border-gold-400/15 p-5"><ShieldCheck className="h-5 w-5 text-gold-400"/><p className="mt-3 text-sm text-slate-400">Accessibility covers keyboard use, semantic HTML, reduced motion, contrast and accessible names.</p></div></div><div><div className="grid gap-3 sm:grid-cols-2">{checks.map(x=><div key={x} className="rounded-xl border border-white/[.08] p-4"><div className="flex gap-2 text-sm font-semibold text-white"><CheckCircle2 className="h-4 w-4 text-emerald-300"/>{x}</div></div>)}</div><div className="mt-4 grid gap-3 sm:grid-cols-2">{access.map(([Icon,label])=><div key={label} className="rounded-xl border border-gold-400/10 p-4"><Icon className="h-4 w-4 text-gold-400"/><p className="mt-3 text-sm font-semibold text-white">{label}</p></div>)}</div></div></div></Section>;
}

export function CapacityIndicator({ availability }: { availability?: string | null }) { if(!availability)return null;return <span className="inline-flex rounded-full border border-emerald-400/20 bg-emerald-400/[.06] px-3 py-2 text-xs font-semibold text-emerald-200">{availability}</span>; }
